# Admin password: generated by Terraform, stored as a SecureString, read by the
# instance at boot. Note: it also lives in Terraform state, so keep state private.

resource "random_password" "splunk_admin" {
  length  = 20
  special = false # alphanumeric only: no quoting problems in user-seed.conf
}

resource "aws_ssm_parameter" "splunk_admin_password" {
  name        = local.splunk_password_param
  description = "Splunk admin password"
  type        = "SecureString"
  value       = random_password.splunk_admin.result
}
